---

name: release

'on':
  push:
    branches:
      - main

jobs:

  aur-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase.
        uses: actions/checkout@v2

      - name: Release AUR package
        uses: jbouter/aur-releaser@v0.0.7
        with:
          pkgname: salt-lint
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
